ssafy_class_note/debugging-v1.1.1/debugging/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('team/', views.team, name='team'),
    path('members/', views.members, name='members'),
]

ssafy_class_note/debugging-v1.1.1/debugging/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/update/', views.update, name='update'),
    path('<int:article_id>/comments/create/', views.comments_create, name='comments_create'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comments_delete, name='comments_delete'),
]

ssafy_class_note/debugging-v1.1.1/debugging/debugging/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls')),
    path('articles/', include('articles.urls')),
]

ssafy_class_note/debugging-v1.1.1/debugging/about/models.py
from django.db import models

# Create your models here.

ssafy_class_note/debugging-v1.1.1/debugging/articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

ssafy_class_note/debugging-v1.1.1/debugging/articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='제목')
    content = forms.CharField(label='내용', widget=forms.Textarea())
    
    class Meta:
        model = Article
        fields = ['title',]


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='댓글', widget=forms.TextInput())
    
    class Meta:
        model = Comment
        fields = ['content',]

ssafy_class_note/debugging-v1.1.1/debugging/about/views.py
from django.shortcuts import render

def team(request):
    return render(request, 'about/team.html')

def members(request):
    starting_members = ['이상해씨', '파이리', '꼬부기']
    return render(request, 'about/members.html', {'startings': startings})

ssafy_class_note/debugging-v1.1.1/debugging/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

def index(request):
    articles = Article.objects.all()
    return render(request, 'articles/index.html', {'articles': articles})
    
def create(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST)
        if article_form.is_valid():
            article = article_form.save()
            return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm()
    return render(request, 'articles/create.html', {'article_form': article_form})

def detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    comment_form = CommentForm()
    return render(request, 'articles/detail.html', {'article': article, 'comment_form': comment_form})

def update(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            article_form.save()
            return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm(instance=article)
    return render(request, 'articles/update.html', {'article_form': article_form})

def delete(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    article.delete()
    return redirect('articles:index')
    
@require_POST
def comments_create(request, article_id):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save()
    return redirect('articles:detail', article_id)

@require_POST
def comments_delete(request, article_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('articles:detail', article_id)

ssafy_class_note/debugging-v1.1.1/debugging/about/templates/about/members.html
{% extends 'base.html' %}

{% load static %}

{% block container %}

<h1>멤버 소개</h1>

<ul>
    {% for starting in startings %}
    <li>{{ starting }}</li>
    {% endfor %}
</ul>

{% endblock %}

ssafy_class_note/debugging-v1.1.1/debugging/about/templates/about/team.html
{% extends 'base.html' %}

{% block container %}

<h1>팀 소개</h1>

<ul>
    <li>인터넷을 더 안전하고, 풍요롭고 좋은 사회로 만듭니다.</li>
</ul>

<img src="{% static 'about/cable.jpg' %}"/>

{% endblock %}

ssafy_class_note/debugging-v1.1.1/debugging/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block container %}

<h1>아티클 생성</h1>

<form method="post">
    {% csrf_token %}
    {{ article_form.as_p }}
    <input type="submit" value="확인"/>
</form>

{% endblock %}

ssafy_class_note/debugging-v1.1.1/debugging/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block container %}

<h1>{{ article.title }}</h1>

<div>
    <div>작성일: {{ article.created_at }}</div>
    <div>수정일: {{ article.updated_at }}</div>
</div>

<p>
    {{ article.content }}
</p>

<div>
    <a href="{% url 'articles:index' %}">목록</a>    
    <a href="{% url 'articles:update' article.pk %}">수정</a>    
    <a href="/articles/{{ article.pk }}/delete/">삭제</a>    
</div>

<hr>

<ul>
    {% for comment in article.comment_set.all %}
    <li>
        {{ comment.content }} - {{ comment.created_at }}
        <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" style="display: inline-block;">
            {% csrf_token %}
            <input type="submit" value="삭제"/>
        </form>
    </li>
    {% endfor %}
</ul>

<form action="{% url 'articles:comments_create' article.pk %}" method="post">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" value="작성"/>
</form>

{% endblock %}

ssafy_class_note/debugging-v1.1.1/debugging/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}

<h1>아티클 목록</h1>

<div>
    <a href="{% url 'articles:create' %}">새 아티클</a>
</div>

<ul>
    {% for article in articles %}
    <li>
        <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

ssafy_class_note/debugging-v1.1.1/debugging/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block container %}

<h1>아티클 수정</h1>

<form method="post">
    {{ article_form.as_p }}
    <input type="submit" value="확인"/>
</form>

{% endblock %}

ssafy_class_note/debugging-v1.1.1/debugging/debugging/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>디버깅</title>
</head>
<body>
    <header>
        <a href="{% url 'articles:index' %}">메인으로</a>
        <a href="{% url 'about:team' %}">팀 소개</a>
        <a href="{% url 'about:members' %}">멤버 소개</a>
    </header>
    <div class="container">
        {% block container %}{% endblock %}
    </div>
</body>
</html>